name: Lint PR

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  commitlint:
    name: Validate PR Title
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: 'npm'

      - run: npm ci

      - name: Validate PR title as commit message
        run: echo "${{ github.event.pull_request.title }}" | npx commitlint
